# A deep dive into DataFrames.jl indexing
# Part 1: indexing in DataFrames.jl by example
### Bogumił Kamiński

What are we going to cover:
* `getindex`, a.k.a. `x[...]`
* `setindex`, a.k.a. `x[...] =`
* `broadcast`, a.k.a. `fun.(x)`
* `broadcat`, a.k.a. `x .= ...`

Indexable types that DataFrames.jl defines:
* `DataFrame`
* `SubDataFrame`
* `DataFrameRow`
* `DataFrameRows`
* `DataFrameColumns`
* `GroupedDataFrame`
* `GroupKeys`
* `GroupKey`
* `StackedVector`
* `RepeatedVector`

### Environment setup

In [1]:
using DataFrames

In [2]:
using CSV

In [3]:
using BenchmarkTools

In [4]:
using Dates

In [5]:
using Statistics

In [6]:
ENV["COLUMNS"] = 500 # allow output up to 500 characters wide not to be truncated when displayed

500

In [7]:
ENV["LINES"] = 15 # we do not need to see too many lines in the examples we work with

15

In [8]:
df = CSV.File("fh_5yrs.csv") |> DataFrame

6852038×8 DataFrame
│ Row     │ date       │ volume │ open    │ high    │ low     │ close   │ adjclose │ symbol │
│         │ Date       │ Int64  │ Float64 │ Float64 │ Float64 │ Float64 │ Float64  │ String │
├─────────┼────────────┼────────┼─────────┼─────────┼─────────┼─────────┼──────────┼────────┤
│ 1       │ 2020-07-02 │ 257500 │ 17.64   │ 17.74   │ 17.62   │ 17.71   │ 17.71    │ AAAU   │
│ 2       │ 2020-07-01 │ 468100 │ 17.73   │ 17.73   │ 17.54   │ 17.68   │ 17.68    │ AAAU   │
│ 3       │ 2020-06-30 │ 319100 │ 17.65   │ 17.8    │ 17.61   │ 17.78   │ 17.78    │ AAAU   │
⋮
│ 6852035 │ 2015-01-09 │ 200    │ 0.15    │ 0.15    │ 0.15    │ 0.15    │ 0.146038 │ ZYXI   │
│ 6852036 │ 2015-01-07 │ 8100   │ 0.14    │ 0.15    │ 0.13    │ 0.15    │ 0.146038 │ ZYXI   │
│ 6852037 │ 2015-01-05 │ 33200  │ 0.22    │ 0.22    │ 0.14    │ 0.16    │ 0.155774 │ ZYXI   │
│ 6852038 │ 2015-01-02 │ 100    │ 0.18    │ 0.18    │ 0.18    │ 0.18    │ 0.175245 │ ZYXI   │

#### Warm up exercises

*Get short description of columns in our data frame*

(see https://github.com/JuliaData/DataFrames.jl/issues/2269 for a discussion of the design decisions here, feel free to comment there if you have an opinion)

*Get information about exact types of the columns stored in the data frame*

*Get names of columns as strings*

*Get names of columns as `Symbol`s*

## DataFrame and SubDataFrame

### `getindex`

Get a single column as a whole without copying

In [9]:
unique([df.date,
        df."date",
        df[!, 1],
        df[!, :date],
        df[!, "date"]])

1-element Array{Array{Date,1},1}:
 [Date("2020-07-02"), Date("2020-07-01"), Date("2020-06-30"), Date("2020-06-29"), Date("2020-06-26"), Date("2020-06-25"), Date("2020-06-24"), Date("2020-06-23"), Date("2020-06-22"), Date("2020-06-19")  …  Date("2015-01-21"), Date("2015-01-20"), Date("2015-01-16"), Date("2015-01-14"), Date("2015-01-13"), Date("2015-01-12"), Date("2015-01-09"), Date("2015-01-07"), Date("2015-01-05"), Date("2015-01-02")]

In [10]:
unique([getproperty(df, :date),
        getproperty(df, "date"),
        getindex(df, !, 1),
        getindex(df, !, :date),
        getindex(df,!, "date")])

1-element Array{Array{Date,1},1}:
 [Date("2020-07-02"), Date("2020-07-01"), Date("2020-06-30"), Date("2020-06-29"), Date("2020-06-26"), Date("2020-06-25"), Date("2020-06-24"), Date("2020-06-23"), Date("2020-06-22"), Date("2020-06-19")  …  Date("2015-01-21"), Date("2015-01-20"), Date("2015-01-16"), Date("2015-01-14"), Date("2015-01-13"), Date("2015-01-12"), Date("2015-01-09"), Date("2015-01-07"), Date("2015-01-05"), Date("2015-01-02")]

Get a single column as a whole with copying

In [11]:
unique([copy(df.date),
        copy(df."date"),
        df[:, 1],
        df[:, :date],
        df[:, "date"]])

1-element Array{Array{Date,1},1}:
 [Date("2020-07-02"), Date("2020-07-01"), Date("2020-06-30"), Date("2020-06-29"), Date("2020-06-26"), Date("2020-06-25"), Date("2020-06-24"), Date("2020-06-23"), Date("2020-06-22"), Date("2020-06-19")  …  Date("2015-01-21"), Date("2015-01-20"), Date("2015-01-16"), Date("2015-01-14"), Date("2015-01-13"), Date("2015-01-12"), Date("2015-01-09"), Date("2015-01-07"), Date("2015-01-05"), Date("2015-01-02")]

Let us compare the performance of various ways to get a column without copying

In [12]:
@btime $df.date
@btime $df."date"
@btime $df[!, 1]
@btime $df[!, :date]
@btime $df[!, "date"];

  13.326 ns (0 allocations: 0 bytes)
  36.995 ns (0 allocations: 0 bytes)
  4.599 ns (0 allocations: 0 bytes)
  13.327 ns (0 allocations: 0 bytes)
  36.894 ns (0 allocations: 0 bytes)


#### Exercise

Check the same but with copying

Do you think it really matters in practice how fast is an access to column of a data frame?

Let us check how lookup speed scales with the number of columns:

In [13]:
@time df_tmp = DataFrame(ones(1, 100_000))

  0.069699 seconds (599.57 k allocations: 47.574 MiB)


1×100000 DataFrame. Omitted printing of 99951 columns
│ Row │ x1      │ x2      │ x3      │ x4      │ x5      │ x6      │ x7      │ x8      │ x9      │ x10     │ x11     │ x12     │ x13     │ x14     │ x15     │ x16     │ x17     │ x18     │ x19     │ x20     │ x21     │ x22     │ x23     │ x24     │ x25     │ x26     │ x27     │ x28     │ x29     │ x30     │ x31     │ x32     │ x33     │ x34     │ x35     │ x36     │ x37     │ x38     │ x39     │ x40     │ x41     │ x42     │ x43     │ x44     │ x45     │ x46     │ x47     │ x48     │ x49     │
│     │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │
├─────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ 1   │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │ 1.0     │

In [14]:
@btime $df_tmp.x100000
@btime $df_tmp."x100000"
@btime $df_tmp[!, 100000];

  15.029 ns (0 allocations: 0 bytes)
  50.100 ns (0 allocations: 0 bytes)
  4.599 ns (0 allocations: 0 bytes)


Get a single column, but take a subset of rows: you can either make a copy or get a view

In [15]:
df[1:2, :date]

2-element Array{Date,1}:
 2020-07-02
 2020-07-01

In [16]:
view(df, 1:2, :date)

2-element view(::Array{Date,1}, 1:2) with eltype Date:
 2020-07-02
 2020-07-01

this is the same as:

In [17]:
df.date[1:2]

2-element Array{Date,1}:
 2020-07-02
 2020-07-01

In [18]:
view(df.date, 1:2)

2-element view(::Array{Date,1}, 1:2) with eltype Date:
 2020-07-02
 2020-07-01

you can use `Not` for inverted selection

In [19]:
df[Not(3:end), :date]

2-element Array{Date,1}:
 2020-07-02
 2020-07-01

Get a single cell in a data frame: you can either get a value or a view

In [20]:
df[1, :date]

2020-07-02

In [21]:
view(df, 1, :date)

0-dimensional view(::Array{Date,1}, 1) with eltype Date:
Date("2020-07-02")

#### Exercise

In what case you might want to use a view instead of getting a value?

Check what is the consequence of running the following lines:

In [22]:
tmp_cell = view(df, 1, :date)

0-dimensional view(::Array{Date,1}, 1) with eltype Date:
Date("2020-07-02")

In [23]:
tmp_cell2 = getindex(df, 1, :date)

2020-07-02

In [24]:
tmp_cell[] = Date("2222-07-02")

2222-07-02

Revert the change we have just made

To conclude note that with `view` there is not difference between `!` and `:`:

In [25]:
@view df[!, 1]

6852038-element view(::Array{Date,1}, :) with eltype Date:
 2222-07-02
 2020-07-01
 2020-06-30
 2020-06-29
 2020-06-26
 ⋮
 2015-01-12
 2015-01-09
 2015-01-07
 2015-01-05
 2015-01-02

In [26]:
@view df[:, 1]

6852038-element view(::Array{Date,1}, :) with eltype Date:
 2222-07-02
 2020-07-01
 2020-06-30
 2020-06-29
 2020-06-26
 ⋮
 2015-01-12
 2015-01-09
 2015-01-07
 2015-01-05
 2015-01-02

Summary:

> passing a single column as an integer, `Symbol` or string drops one dimension of
> a data frame and allows you to select or subset a column from it

Multiple column selection options:
* a vector of `Symbol` (does not have to be a subtype of `AbstractVector{Symbol}`);
* a vector of `AbstractString` (does not have to be a subtype of `AbstractVector{<:AbstractString}`);
* a vector of `Integer` other than `Bool` (does not have to be a subtype of `AbstractVector{<:Integer}`);
* a vector of `Bool` that has to be a subtype of `AbstractVector{Bool}`;
* a regular expression, which gets expanded to a vector of matching column names;
* a `Not` expression;
* an `All` or `Between` expression;
* a colon literal :.

The type of output depends on the row selecor:
* if it is a single row you get a `DataFrameRow` (a dimension is dropped)
* if it is a collection of rows you get a data frame

Single row selection is always a view that is `DataFrameRow`:

In [27]:
df[1, [:date]]

DataFrameRow
│ Row │ date       │
│     │ Date       │
├─────┼────────────┤
│ 1   │ 2222-07-02 │

In [28]:
@view df[1, [:date]]

DataFrameRow
│ Row │ date       │
│     │ Date       │
├─────┼────────────┤
│ 1   │ 2222-07-02 │

Multiple row selection is a `DataFrame` for `getindex`:

In [29]:
df[1:2, 1:2]

2×2 DataFrame
│ Row │ date       │ volume │
│     │ Date       │ Int64  │
├─────┼────────────┼────────┤
│ 1   │ 2222-07-02 │ 257500 │
│ 2   │ 2020-07-01 │ 468100 │

In [30]:
df2 = df[!, 1:2] # this does not copy columns

6852038×2 DataFrame
│ Row     │ date       │ volume │
│         │ Date       │ Int64  │
├─────────┼────────────┼────────┤
│ 1       │ 2222-07-02 │ 257500 │
│ 2       │ 2020-07-01 │ 468100 │
│ 3       │ 2020-06-30 │ 319100 │
⋮
│ 6852035 │ 2015-01-09 │ 200    │
│ 6852036 │ 2015-01-07 │ 8100   │
│ 6852037 │ 2015-01-05 │ 33200  │
│ 6852038 │ 2015-01-02 │ 100    │

In [31]:
df2.date === df.date

true

Using `view` creates a `SubDataFrame`

In [32]:
df3 = view(df, 1:2, 1:2)

2×2 SubDataFrame
│ Row │ date       │ volume │
│     │ Date       │ Int64  │
├─────┼────────────┼────────┤
│ 1   │ 2222-07-02 │ 257500 │
│ 2   │ 2020-07-01 │ 468100 │

In [33]:
typeof(df3)

SubDataFrame{DataFrame,DataFrames.SubIndex{DataFrames.Index,UnitRange{Int64},UnitRange{Int64}},UnitRange{Int64}}

For `view` using `:` and `!` gives you the same result:

In [34]:
dump(view(df, !, :))

SubDataFrame{DataFrame,DataFrames.Index,Base.OneTo{Int64}}
  parent: DataFrame
    columns: Array{AbstractArray{T,1} where T}((8,))
      1: Array{Date}((6852038,))
        1: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 811386
        2: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 737607
        3: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 737606
        4: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 737605
        5: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 737602
        ...
        6852034: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 735610
        6852035: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 735607
      

In [35]:
dump(view(df, :, :))

SubDataFrame{DataFrame,DataFrames.Index,Base.OneTo{Int64}}
  parent: DataFrame
    columns: Array{AbstractArray{T,1} where T}((8,))
      1: Array{Date}((6852038,))
        1: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 811386
        2: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 737607
        3: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 737606
        4: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 737605
        5: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 737602
        ...
        6852034: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 735610
        6852035: Date
          instant: Dates.UTInstant{Day}
            periods: Day
              value: Int64 735607
      

Normally when you modify the parent of a `SubDataFrame` (or `DataFrameRow`) you may get an error when trying to access it:

In [36]:
df4 = DataFrame(reshape(1:12, 3, 4))

3×4 DataFrame
│ Row │ x1    │ x2    │ x3    │ x4    │
│     │ Int64 │ Int64 │ Int64 │ Int64 │
├─────┼───────┼───────┼───────┼───────┤
│ 1   │ 1     │ 4     │ 7     │ 10    │
│ 2   │ 2     │ 5     │ 8     │ 11    │
│ 3   │ 3     │ 6     │ 9     │ 12    │

In [37]:
df4_v = view(df4, 1:2, 1:3)

2×3 SubDataFrame
│ Row │ x1    │ x2    │ x3    │
│     │ Int64 │ Int64 │ Int64 │
├─────┼───────┼───────┼───────┤
│ 1   │ 1     │ 4     │ 7     │
│ 2   │ 2     │ 5     │ 8     │

In [38]:
select!(df4, 1)

3×1 DataFrame
│ Row │ x1    │
│     │ Int64 │
├─────┼───────┤
│ 1   │ 1     │
│ 2   │ 2     │
│ 3   │ 3     │

In [39]:
df4_v

BoundsError: BoundsError: attempt to access 1-element Array{Symbol,1} at index [1:3]

A special case is when you use `:` as a column selection with a `view`. In this case the `SubDataFrame` and `DataFrameRow` always get updated with the changed columns:

In [40]:
df4 = DataFrame(reshape(1:12, 3, 4))

3×4 DataFrame
│ Row │ x1    │ x2    │ x3    │ x4    │
│     │ Int64 │ Int64 │ Int64 │ Int64 │
├─────┼───────┼───────┼───────┼───────┤
│ 1   │ 1     │ 4     │ 7     │ 10    │
│ 2   │ 2     │ 5     │ 8     │ 11    │
│ 3   │ 3     │ 6     │ 9     │ 12    │

In [41]:
df4_v = view(df4, 1:2, :)

2×4 SubDataFrame
│ Row │ x1    │ x2    │ x3    │ x4    │
│     │ Int64 │ Int64 │ Int64 │ Int64 │
├─────┼───────┼───────┼───────┼───────┤
│ 1   │ 1     │ 4     │ 7     │ 10    │
│ 2   │ 2     │ 5     │ 8     │ 11    │

In [42]:
select!(df4, 1, :x2 => :newcol)

3×2 DataFrame
│ Row │ x1    │ newcol │
│     │ Int64 │ Int64  │
├─────┼───────┼────────┤
│ 1   │ 1     │ 4      │
│ 2   │ 2     │ 5      │
│ 3   │ 3     │ 6      │

In [43]:
df4_v

2×2 SubDataFrame
│ Row │ x1    │ newcol │
│     │ Int64 │ Int64  │
├─────┼───────┼────────┤
│ 1   │ 1     │ 4      │
│ 2   │ 2     │ 5      │

The reason for this behavior is that subsetting of a data frame by only rows (and taking all columns) is very common, and in this case we can create and index such views much faster. In particular `DataFrameRow`s produced by `eachrow` are efficient this way:

In [44]:
@btime mean(x -> x.open, eachrow(df))

  1.033 s (34259693 allocations: 522.76 MiB)


298.08612911254846

In [45]:
@btime mean(i -> df[i, :open], 1:nrow(df))

  1.276 s (41111214 allocations: 627.31 MiB)


298.08612911254846

Of course, type-stable operation would be faster (but sometimes processing data row-wise is more convenient):

In [46]:
@btime mean(df.open)

  2.980 ms (1 allocation: 16 bytes)


298.08612911254846

or, if your table is not very wide (so that you are not penalized by the compilation cost of `NamedTuple`) you can use:

In [47]:
@btime mean(x -> x.open, Tables.namedtupleiterator(df))

  10.506 ms (18 allocations: 1.31 KiB)


298.0861291125547

Note though that `DataFrameRow` allows you to modify the source data frame, while iterating `NamedTuple`s is read-only (more on `setindex!` later).